# Configuración de la aplicación Flask
flask:
  image: "juanarillo/kubernetes_practica:v5"
  replicas: 2
  message: "Este texto es una variable desde values.yaml"
  cpuRequest: "125m"
  memoryRequest: "256Mi"
  cpuLimit: "250m"
  memoryLimit: "512Mi"

# Configuración del servicio
service:
  type: NodePort 
  port: 5000

# Redis Configuración
redis:
  image:
    repository: redis
    tag: 7.0
  port: 6379
  password: "mipassword" 
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: standard

# HPA Configuración
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  cpuThreshold: 70

# Ingress Configuración
ingress:
  enabled: true
  host: "flask-app.local"