apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: {{ .Values.flask.replicas }}
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: {{ .Values.flask.image }}
        resources:
            requests:
              cpu: "{{ .Values.flask.cpuRequest }}"
              memory: "{{ .Values.flask.memoryRequest }}"
            limits:
              cpu: "{{ .Values.flask.cpuLimit }}"
              memory: "{{ .Values.flask.memoryLimit }}"
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_MESSAGE
          value: "{{ .Values.flask.message }}"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password