apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  {{- $chartName := .Chart.Name }}
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
        {{- range $path := $host.paths }}
          - path: {{ $path.path }}
            pathType: {{ $path.pathType }}
            backend:
              service:
                name: {{ $chartName }}-svc
                port:
                  number: 5000
        {{- end }}
   {{- end }}