apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.persistentVolume.size }}
  storageClassName: {{ .Values.redis.persistentVolume.storageClass }}