apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-redis
  labels:
    app: {{ .Chart.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-redis
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-redis
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image }}"
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-redis-secret
                  key: redisPassword
          volumeMounts:
            - mountPath: /data
              name: redis-persistent-storage
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-redis-pvc